---
  - name: playbook
    hosts: webservers
    become: yes
    become_users: root
    tasks:
      - name: ensure apache is at latest version
        yum: 
          name: httpd
          state: latest
      - name: ensure apache is running
        service:
          name: httpd
          state: started